# Generated by Django 4.2.4 on 2023-08-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_watering_options_alter_plant_bears_fruit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandscapingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('made_of', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='landscaping_materials',
            field=models.ManyToManyField(to='main_app.landscapingmaterial'),
        ),
    ]
