# Generated by Django 4.2.4 on 2023-08-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_landscapingmaterial_plant_landscaping_materials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LandscapingMaterial',
            new_name='Material',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='landscaping_materials',
            new_name='materials',
        ),
    ]
